version: "3.9"
services:
    db:
        build: ./db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres

    backend:
        build: ./backend
        ports:
            - "5000:5000"
        depends_on:
            - db

    frontend:
        build: ./luxonis-fe
        ports:
            - "8080:8080"
