\c postgres;

DROP DATABASE luxonis;

CREATE DATABASE luxonis;

\c luxonis;

CREATE TABLE apartments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    link VARCHAR(255),
    title VARCHAR(255),
    location VARCHAR(255),
    price VARCHAR(255),
    image VARCHAR(255),
    CONSTRAINT pk_apartments PRIMARY KEY (id)
);

COPY apartments (link, title, location, price, image) FROM '/data.csv' DELIMITER ',' CSV;

